#!/usr/bin/env python3
from tkinter import *
from selenium import webdriver
import time


def s_command(textbox,textbox1,l,l1,s):
    usr = textbox.get()
    psd = textbox1.get()
    driver = webdriver.Firefox()
    driver.get("https://github.com/login")
    time.sleep(1)
    username = driver.find_element_by_xpath('//*[@id="login_field"]')
    username.send_keys(usr)
    password = driver.find_element_by_xpath('//*[@id="password"]')
    password.send_keys(psd)
    sub = driver.find_element_by_xpath('/html/body/div[3]/main/div/form/div[3]/input[8]')
    sub.click()
    l.place_forget()
    l1.place_forget()
    textbox1.place_forget()
    textbox.place_forget()
    s.place_forget()
def t_command(textbox,textbox1,l,l1,s):
    usr = textbox.get()
    psd = textbox1.get()
    driver = webdriver.Firefox()
    driver.get("https://twitter.com/login")
    time.sleep(1)
    username = driver.find_element_by_xpath('/html/body/div[1]/div[2]/div/div/div[1]/form/fieldset/div[1]/input')
    username.send_keys(usr)
    password = driver.find_element_by_xpath('/html/body/div[1]/div[2]/div/div/div[1]/form/fieldset/div[2]/input')
    password.send_keys(psd)
    sub = driver.find_element_by_xpath('/html/body/div[1]/div[2]/div/div/div[1]/form/div[2]/button')
    sub.click()
    l.place_forget()
    l1.place_forget()
    textbox1.place_forget()
    textbox.place_forget()
    s.place_forget()
def u_command(textbox,textbox1,l,l1,s):
    usr = textbox.get()
    psd = textbox1.get()
    driver = webdriver.Firefox()
    driver.get("https://www.instagram.com/accounts/login/")
    time.sleep(1)
    username = driver.find_element_by_xpath('/html/body/div[1]/section/main/div/article/div/div[1]/div/form/div[2]/div/label/input')
    username.send_keys(usr)
    password = driver.find_element_by_xpath('/html/body/div[1]/section/main/div/article/div/div[1]/div/form/div[3]/div/label/input')
    password.send_keys(psd)
    sub = driver.find_element_by_xpath('/html/body/div[1]/section/main/div/article/div/div[1]/div/form/div[4]')
    sub.click()
    l.place_forget()
    l1.place_forget()
    textbox1.place_forget()
    textbox.place_forget()
    s.place_forget()

def open_git():
    l= Label(root, text='user id / email :', font=26)
    l.place(x=165, y=345)
    textbox = Entry(root)
    textbox.place(x=165,y=365)
    l1= Label(root, text='password:', font=26)
    l1.place(x=165, y=395)
    textbox1 = Entry(root,show="*")
    textbox1.place(x=165, y=415)
    s = Button(root, text="Submit",command = lambda: s_command(textbox,textbox1,l,l1,s))
    s.place(x=210, y=445)
def open_twitter():
    l = Label(root, text='user id / email :', font=26)
    l.place(x=165, y=345)
    textbox = Entry(root)
    textbox.place(x=165, y=365)
    l1 = Label(root, text='password:', font=26)
    l1.place(x=165, y=395)
    textbox1 = Entry(root, show="*")
    textbox1.place(x=165, y=415)
    t = Button(root, text="Submit", command=lambda: t_command(textbox, textbox1, l, l1, t))
    t.place(x=210, y=445)
def open_insta():
    l = Label(root, text='user id / email :', font=26)
    l.place(x=165, y=345)
    textbox = Entry(root)
    textbox.place(x=165, y=365)
    l1 = Label(root, text='password:', font=26)
    l1.place(x=165, y=395)
    textbox1 = Entry(root, show="*")
    textbox1.place(x=165, y=415)
    u = Button(root, text="Submit", command=lambda: u_command(textbox, textbox1, l, l1, u))
    u.place(x=210, y=445)


if __name__ == "__main__":
    root = Tk()
    root.geometry("495x495+700+300")
    root.resizable(False, False)
    Label(root, text="__________________________________________________________________________").place(x=0,y=25)
    l = Label(root, text='open GitHub and login to your mainpage ',font=26).place(x=90,y=50)
    s =Button(root, text = "Start",command = open_git)
    s.place(x=250,y=110,anchor=CENTER)
    Label(root, text="__________________________________________________________________________").place(x=0, y=125)
    l1 = Label(root, text='open Twitter and view your feed ', font=26).place(x=90, y=150)
    s1 = Button(root, text="Start",command = open_twitter)
    s1.place(x=250, y=210, anchor=CENTER)
    Label(root, text="__________________________________________________________________________").place(x=0, y=225)
    l2 = Label(root, text='open Instagram and view your feed ', font=26).place(x=90, y=250)
    s2 = Button(root, text="Start", command = open_insta)
    s2.place(x=250, y=310, anchor=CENTER)
    Label(root, text="__________________________________________________________________________").place(x=0, y=325)


    root.mainloop()